os:
  - linux

language: go
sudo: false

go:
  - "tip"
  - "1.13"
  - "1.12"
  - "1.11"

script:
  - make lint
  - make test
  - make bench

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - tiago4orion@gmail.com
    - tiagokatcipis@gmail.com
    - vitorarins@gmail.com
