os:
  - linux

language: go
sudo: false

go:
  - "tip"
  - "1.10"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go test ./... -bench .

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email:
    - tiago4orion@gmail.com
    - tiagokatcipis@gmail.com
    - vitorarins@gmail.com
