name: Test and Benchmarks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: test and benchmarks
    strategy:
      matrix:
        os: [macos-11, ubuntu-20.04, windows-2019]
        go: [1.16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go ${{matrix.go}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: tests
        run: make test

      - name: benchmarks
        run: make bench
