name: Test and Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Run test and benchmarks
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
        go: ["1.16", "1.17"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go ${{matrix.go}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: tests
        run: make test

      - name: benchmarks
        run: make bench
